-- PLTS monitoring storage for the trusted Render backend.
-- Run this once in Supabase Dashboard -> SQL Editor.

create table if not exists public.monitoring_current (
  id smallint primary key default 1 check (id = 1),
  run_id text not null,
  scraped_at timestamptz not null,
  payload jsonb not null,
  summary jsonb not null default '{}'::jsonb,
  updated_at timestamptz not null default now()
);

create table if not exists public.monitoring_snapshots (
  id bigint generated by default as identity primary key,
  run_id text not null unique,
  scraped_at timestamptz not null,
  payload jsonb not null,
  summary jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists monitoring_snapshots_scraped_at_idx
  on public.monitoring_snapshots (scraped_at desc);

create table if not exists public.monitoring_site_daily (
  platform text not null,
  station_id text not null,
  station_name text not null,
  bucket_date date not null,
  energy_kwh double precision,
  revenue_amount double precision,
  currency text,
  source_scraped_at timestamptz not null,
  updated_at timestamptz not null default now(),
  primary key (platform, station_id, bucket_date)
);

create index if not exists monitoring_site_daily_station_date_idx
  on public.monitoring_site_daily (platform, station_id, bucket_date desc);

-- The browser never talks to these tables directly. Keep them private and let
-- the Render backend use a Supabase secret/service-role key.
alter table public.monitoring_current enable row level security;
alter table public.monitoring_snapshots enable row level security;
alter table public.monitoring_site_daily enable row level security;

revoke all on table public.monitoring_current from anon, authenticated;
revoke all on table public.monitoring_snapshots from anon, authenticated;
revoke all on table public.monitoring_site_daily from anon, authenticated;

grant all on table public.monitoring_current to service_role;
grant all on table public.monitoring_snapshots to service_role;
grant all on table public.monitoring_site_daily to service_role;
grant usage, select on sequence public.monitoring_snapshots_id_seq to service_role;
